# fly.toml app configuration file for Helpers Platform API

app = "helpers-platform-api"
primary_region = "iad"  # Washington DC - adjust based on your primary user base
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 3001
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    method = "get"
    path = "/health"
    protocol = "http"

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

# Scaling configuration
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Auto-scaling rules
[http_service.machine_config]
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1

# Regions for deployment (adjust based on your user base)
[deploy]
  strategy = "rolling"
  max_unavailable = 0.5

# Monitoring and metrics
[metrics]
  port = 9091
  path = "/metrics"
